"""
Permission matrix for Fracttal PRM RBAC system.

Permission strings follow the pattern: {resource}:{action}

Resources: partner_organization, partner_profile, partner_user,
           deal_registration, quote, training, asset, report,
           user_management, system_config

Actions: create, read_own, read_all, update_own, update_all,
         delete, approve, reject, export
"""
from roles import UserRole


PERMISSIONS: dict[str, set[str]] = {

    UserRole.partner_user: {
        "partner_organization:read_own",
        "partner_profile:read_own",
        "deal_registration:create",
        "deal_registration:read_own",
        "deal_registration:update_own",
        "training:read_own",
        "asset:read_own",
        "quote:read_own",
    },

    UserRole.partner_admin: {
        "partner_organization:read_own",
        "partner_organization:update_own",
        "partner_profile:read_own",
        "partner_profile:update_own",
        "partner_user:create",
        "partner_user:read_own",
        "partner_user:update_own",
        "partner_user:delete",
        "deal_registration:create",
        "deal_registration:read_own",
        "deal_registration:update_own",
        "training:read_own",
        "asset:read_own",
        "quote:create",
        "quote:read_own",
        "quote:update_own",
        "report:read_own",
        "report:export",
    },

    UserRole.channel_manager: {
        "partner_organization:read_all",
        "partner_organization:update_all",
        "partner_profile:read_all",
        "partner_profile:update_all",
        "partner_user:read_all",
        "deal_registration:read_all",
        "deal_registration:update_all",
        "deal_registration:approve",
        "deal_registration:reject",
        "quote:read_all",
        "quote:approve",
        "quote:reject",
        "training:read_own",
        "asset:read_all",
        "report:read_all",
        "report:export",
    },

    UserRole.channel_ops_admin: {
        "partner_organization:create",
        "partner_organization:read_all",
        "partner_organization:update_all",
        "partner_organization:delete",
        "partner_profile:read_all",
        "partner_profile:update_all",
        "partner_user:create",
        "partner_user:read_all",
        "partner_user:update_all",
        "partner_user:delete",
        "deal_registration:read_all",
        "deal_registration:update_all",
        "deal_registration:approve",
        "deal_registration:reject",
        "quote:read_all",
        "quote:update_all",
        "quote:approve",
        "quote:reject",
        "training:create",
        "training:read_all",
        "training:update_all",
        "training:delete",
        "asset:create",
        "asset:read_all",
        "asset:update_all",
        "asset:delete",
        "report:read_all",
        "report:export",
        "system_config:read_all",
        "system_config:update_all",
    },

    UserRole.sales_rep: {
        "partner_organization:read_all",
        "partner_profile:read_all",
        "deal_registration:read_all",
        "deal_registration:update_all",
        "quote:read_all",
        "report:read_all",
        "report:export",
    },

    UserRole.sales_ops: {
        "partner_organization:read_all",
        "partner_profile:read_all",
        "deal_registration:read_all",
        "quote:create",
        "quote:read_all",
        "quote:update_all",
        "quote:approve",
        "quote:reject",
        "quote:export",
        "report:read_all",
        "report:export",
        "system_config:read_all",
        "system_config:update_all",
    },

    UserRole.finance_approver: {
        "partner_organization:read_all",
        "deal_registration:read_all",
        "quote:read_all",
        "quote:approve",
        "quote:reject",
        "report:read_all",
        "report:export",
    },

    UserRole.system_admin: {
        "partner_organization:create",
        "partner_organization:read_all",
        "partner_organization:update_all",
        "partner_organization:delete",
        "partner_profile:read_all",
        "partner_profile:update_all",
        "partner_user:create",
        "partner_user:read_all",
        "partner_user:update_all",
        "partner_user:delete",
        "deal_registration:create",
        "deal_registration:read_all",
        "deal_registration:update_all",
        "deal_registration:approve",
        "deal_registration:reject",
        "deal_registration:delete",
        "quote:create",
        "quote:read_all",
        "quote:update_all",
        "quote:approve",
        "quote:reject",
        "quote:delete",
        "quote:export",
        "training:create",
        "training:read_all",
        "training:update_all",
        "training:delete",
        "asset:create",
        "asset:read_all",
        "asset:update_all",
        "asset:delete",
        "report:read_all",
        "report:export",
        "user_management:create",
        "user_management:read_all",
        "user_management:update_all",
        "user_management:delete",
        "system_config:read_all",
        "system_config:update_all",
    },
}


def has_permission(role: str, permission: str) -> bool:
    """Check if a role has a specific permission."""
    return permission in PERMISSIONS.get(role, set())
